insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('lorem', 'Jasmin', 'Sorel', 'jsorel0@usgs.gov', false, false);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('in', 'Marnie', 'Crimpe', 'mcrimpe1@opera.com', true, true);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('tempus', 'Melantha', 'Burness', 'mburness2@creativecommons.org', true, false);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('cum', 'Ward', 'D''Errico', 'wderrico3@japanpost.jp', true, false);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('curabitur', 'Saidee', 'Butter', 'sbutter4@xing.com', true, true);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('consequat', 'Jeffy', 'Davey', 'jdavey5@clickbank.net', true, true);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('aenean', 'Madel', 'McAuliffe', 'mmcauliffe6@howstuffworks.com', false, false);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('sed', 'Kelcey', 'Brashaw', 'kbrashaw7@netscape.com', false, true);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('elit', 'Dyann', 'Keilty', 'dkeilty8@twitpic.com', false, true);
insert into users (password, first_name, last_name, email, is_contributor, is_admin) values ('dui', 'Lula', 'Dunsire', 'ldunsire9@statcounter.com', false, false);

insert into addresses (address_line1, postal_code, city, country) values ('418 Independence Alley', 1182, 'Huangma', 'China');
insert into addresses (address_line1, postal_code, city, country) values ('76652 8th Center', 4982, 'Radzyń Chełmiński', 'Poland');
insert into addresses (address_line1, postal_code, city, country) values ('6 Hazelcrest Parkway', 1063, 'Ribafria', 'Portugal');
insert into addresses (address_line1, postal_code, city, country) values ('624 Maywood Crossing', 388, 'Hufang', 'China');
insert into addresses (address_line1, postal_code, city, country) values ('30077 Gale Lane', 8369, 'Sambongmulyo', 'Indonesia');
insert into addresses (address_line1, postal_code, city, country) values ('93752 Straubel Trail', 9567, 'Waśniów', 'Poland');
insert into addresses (address_line1, postal_code, city, country) values ('78 Stuart Terrace', 5279, 'Titiakar', 'Indonesia');
insert into addresses (address_line1, postal_code, city, country) values ('17 Declaration Terrace', 2900, 'Besuk Selatan', 'Indonesia');
insert into addresses (address_line1, postal_code, city, country) values ('6403 Norway Maple Lane', 8717, 'Tangxi', 'China');
insert into addresses (address_line1, postal_code, city, country) values ('373 Park Meadow Avenue', 4182, 'Miaoshi', 'China');

insert into exercises (name, description, target_muscle_group, image, video_link) values ('Crunches', 'Lying on your back, feet on the gound and hands behind your head, crunch up and bring hands to touch knees before rolling back to the ground', 'Core', 'https://image.shutterstock.com/image-vector/woman-doing-crunches-gym-belly-600w-1234348741.jpg', 'https://www.youtube.com/watch?v=Xyd_fa5zoEU');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Side plank', 'Start with elbow, hip and forearm on the floor. Raise hip until armpit level.', 'Core', 'https://image.shutterstock.com/image-photo/side-plank-exercise-athletic-woman-600w-1751568857.jpg', 'https://www.youtube.com/watch?v=K2VljzCC16g');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Plank', 'With both forearms and toes on the floor, keep head, shoulders, hips and knees aligned', 'Core', 'https://image.shutterstock.com/image-photo/strong-beautiful-fitness-girl-athletic-600w-1497529061.jpg', 'https://www.youtube.com/watch?v=pSHjTRCQxIw');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Russian twists', 'Sit on the floor with you knees bend. Keep knees togetehr and feet together. Interlacer your fingers, strech your arms and twist as far as possible to each side', 'Core', 'https://as1.ftcdn.net/v2/jpg/00/82/28/00/1000_F_82280003_lpOmNiqJbXbzadkBzxQxzVLCH2in44vf.jpg', 'https://www.youtube.com/watch?v=wkD8rjkodUI');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Jumping jacks', 'Stand feet together, arms by your side. Jump your feet to the sides, wider than hip distance while bring your straight arms to meet above your head.', 'Full body', 'https://image.shutterstock.com/image-vector/jumping-jacks-exercise-girl-workout-600w-1633713496.jpg', 'https://www.youtube.com/watch?v=iSSAk4XCsRA');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Push up', 'Feet and hands on the floor, arms straight, body rigid Bend arms till you nose almost touces the floo, and lift yourself back up to starting position. ', 'Full body', 'https://media.istockphoto.com/vectors/push-ups-exercises-and-yoga-vector-illustration-vector-id1161576679?s=612x612', 'https://www.youtube.com/watch?v=_l3ySVKYVJ8');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Burpee', 'Start by standing feet hip distance apart arms by your side. Put your hands to the floor and jump your feet back to push up position. Jump your feet back between your hands and jum up with arms above your head.', 'Full body', 'https://media.istockphoto.com/vectors/exercise-guide-with-woman-doing-the-squat-thrust-burpee-position-in-3-vector-id1147316374?s=612x612', 'https://www.youtube.com/watch?v=TU8QYVW0gDU');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Reverse crunches', 'Start lying on your back, legs straigt, arms by your side. Keep feet together while you raise your legs above your hips.', 'Full body', 'https://image.shutterstock.com/image-vector/girl-doing-reverse-crunch-exercise-600w-1709322895.jpg', 'https://www.youtube.com/watch?v=gAyTBB4lm3I');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Squat', 'Start standing with feet almost shoulderwith apart. Without letting your knees go over your toes, bend knees and lower down till hips are below knees.', 'Lower body', 'https://thumbs.dreamstime.com/z/squat-sport-exersice-silhouettes-woman-doing-exercise-workout-training-squat-sport-exersice-silhouettes-woman-doing-exercise-119786597.jpg', 'http://dummyimage.com/170x100.png/cc0000/ffffff');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Jump squat', 'Start standing with feet almost shoulderwith apart. Without letting your knees go over your toes, bend knees and lower down till hips are below knees. Come up into a jump.', 'Lower body', 'https://image.shutterstock.com/image-vector/man-doing-jump-squat-exercise-600w-1991346719.jpg', 'https://www.youtube.com/watch?v=xqvCmoLULNY');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Lunges', 'Start standing upright hands on hips. Step forward with one foot.Back knee touches ground below hip', 'Lower body', 'https://thumbs.dreamstime.com/z/man-doing-dumbbell-walking-lunges-exercise-man-doing-dumbbell-walking-lunges-exercise-flat-vector-illustration-isolated-white-230812187.jpg', 'https://www.youtube.com/watch?v=QOVaHwm-Q6U');
insert into exercises (name, description, target_muscle_group, image, video_link) values ('Hip raises', 'Start lying on your back, knees bend, feet on the floor. Lift hips off the floor until fully extended shouldblades lifted off the floor. Slowly lower back down', 'Lower body', 'https://image.shutterstock.com/z/stock-photo-hip-raises-360740402.jpg', 'https://www.youtube.com/watch?v=fDP6O_aJpDg');

insert into sets (exercise_repetitions, exercise_id) values (1,10));
insert into sets (exercise_repetitions, exercise_id) values (2,10);
insert into sets (exercise_repetitions, exercise_id) values (3,30);
insert into sets (exercise_repetitions, exercise_id) values (4,40);
insert into sets (exercise_repetitions) values (45);
insert into sets (exercise_repetitions) values (83);
insert into sets (exercise_repetitions) values (41);
insert into sets (exercise_repetitions) values (11);
insert into sets (exercise_repetitions) values (95);
insert into sets (exercise_repetitions) values (94);
insert into sets (exercise_repetitions) values (60);
insert into sets (exercise_repetitions) values (37);
insert into sets (exercise_repetitions) values (47);

insert into profiles (weight, height, medical_conditions, disabilities) values (65, 17, 'pede', 'in');
insert into profiles (weight, height, medical_conditions, disabilities) values (13, 49, null, null);
insert into profiles (weight, height, medical_conditions, disabilities) values (81, 5, 'in', 'elit');
insert into profiles (weight, height, medical_conditions, disabilities) values (93, 92, null, null);
insert into profiles (weight, height, medical_conditions, disabilities) values (57, 70, null, null);
insert into profiles (weight, height, medical_conditions, disabilities) values (97, 64, null, null);
insert into profiles (weight, height, medical_conditions, disabilities) values (33, 73, null, null);
insert into profiles (weight, height, medical_conditions, disabilities) values (16, 82, 'congue', 'dui');
insert into profiles (weight, height, medical_conditions, disabilities) values (42, 59, null, null);
insert into profiles (weight, height, medical_conditions, disabilities) values (24, 78, null, null);

insert into goals (end_date, achieved) values ('2021-06-30', false);
insert into goals (end_date, achieved) values ('2021-10-16', true);
insert into goals (end_date, achieved) values ('2021-09-06', true);
insert into goals (end_date, achieved) values ('2021-12-08', true);
insert into goals (end_date, achieved) values ('2021-04-10', true);
insert into goals (end_date, achieved) values ('2021-12-21', false);
insert into goals (end_date, achieved) values ('2021-07-20', true);
insert into goals (end_date, achieved) values ('2021-05-04', true);
insert into goals (end_date, achieved) values ('2021-05-29', false);
insert into goals (end_date, achieved) values ('2021-03-14', false);

insert into workouts (name, type, complete) values ('orci', 'quam', true);
insert into workouts (name, type, complete) values ('ipsum', 'potenti', true);
insert into workouts (name, type, complete) values ('orci', 'at', true);
insert into workouts (name, type, complete) values ('eu', 'ante', false);
insert into workouts (name, type, complete) values ('id', 'parturient', true);
insert into workouts (name, type, complete) values ('libero', 'ipsum', false);
insert into workouts (name, type, complete) values ('vestibulum', 'ac', false);
insert into workouts (name, type, complete) values ('sit', 'tristique', true);
insert into workouts (name, type, complete) values ('nec', 'accumsan', true);
insert into workouts (name, type, complete) values ('dapibus', 'dui', false);

insert into programs (name, category) values ('gravida', 'vel');
insert into programs (name, category) values ('vel', 'at');
insert into programs (name, category) values ('interdum', 'magna');
insert into programs (name, category) values ('duis', 'ultrices');
insert into programs (name, category) values ('montes', 'leo');
insert into programs (name, category) values ('sit', 'at');
insert into programs (name, category) values ('aliquam', 'tincidunt');
insert into programs (name, category) values ('nulla', 'congue');
insert into programs (name, category) values ('tristique', 'gravida');
insert into programs (name, category) values ('magnis', 'id');